### ISSUE TITLE
Way to 0.1

### ISSUE THREAD

**Issue by tyranron** [tyranron/mr-prober#1]
- Features
    - [ ] HTTP probing
    - [ ] TCP socket probing
    - [ ] UDP socket probing
    - [ ] Unix domain socket probing
    - [ ] Concurrent requests amortization with opt-in custom delay
    - [ ] Verbose mode to show probes details
- Infrastructure
    - [ ] CLI (command-line interface)
    - [ ] Config
    - [ ] Graceful shutdown
    - [ ] Structured logging
- Deployment
    - [ ] Docker image + DockerHub integration (latest/edge)
    - GitHub Actions for CI
        - [ ] check: lint + fmt + test
        - [ ] release: crates.io
- Documentation
    - [ ] Problem explanation and features description
    - [ ] Meaningful usage examples
